### ISSUE TITLE
Bug: Crash when exploring

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#100]
![afbeelding](https://user-images.githubusercontent.com/65736624/96608513-c0754680-12f9-11eb-9990-e729f5ecebe9.png)

Error while testing new nether dimensions in studio mode

Could be related to my config, but the crash seems unrelated to me.

**Comment by svdgoor** [comment]
Caused by: java.lang.NullPointerException
        at com.volmit.iris.gen.nms.v16_2.NMSChunkGenerator16_2_PAPER.buildNoise(NMSChunkGenerator16_2_PAPER.java:421) ~[?:?]
        at net.minecraft.server.v1_16_R2.ChunkStatus.lambda$static$5(ChunkStatus.java:52) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.ChunkStatus$d.doWork(ChunkStatus.java:249) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.ChunkStatus.a(ChunkStatus.java:193) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.PlayerChunkMap.lambda$null$39(PlayerChunkMap.java:1222) ~[patched_1.16.3.jar:git-Paper-240]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.PlayerChunkMap.lambda$b$41(PlayerChunkMap.java:1220) ~[patched_1.16.3.jar:git-Paper-240]
        ... 10 more

Second part to this one. Definitely not a configuration error this time.

**Comment by cyberpwnn** [comment]
Fixed in 1.0.21 (update coming)
