### ISSUE TITLE
FAWE and IRIS

### ISSUE THREAD

**Issue by valenvaio** [VolmitSoftware/Iris#1001]
### Problem

Server startup error with FAWE and IRIS
Purpur version git-Purpur-2014 (MC: 1.20.1)
[FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v2.6.5-SNAPSHOT-518;685248d
[Iris] Enabling Iris v2.7.2-1.20.1

[22:13:46] [Server thread/INFO]: [Iris] Enabling Iris v2.7.2-1.20.1
[22:13:46] [Server thread/INFO]: [Iris] §l§8[§l§aIris§l§8]§r§7: §fLocating NMS Binding for v1_20_R1
[22:13:46] [Server thread/INFO]: [Iris] §l§8[§l§aIris§l§8]§r§7: §fCraftbukkit v1_20_R1  NMSBinding1_20_1 Successfully Bound
[22:13:46] [Server thread/INFO]: [Iris]: Loading ExternalDataProvider...
[22:13:46] [Server thread/INFO]: [Iris]: Version Information: git-Purpur-2014 (MC: 1.20.1) | 1.20.1-R0.1-SNAPSHOT
[22:13:46] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[22:13:46] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[22:13:46] [Server thread/WARN]: Whilst this makes it possible to use BungeeCord, unless access to your server is properly restricted, it also opens>
[22:13:46] [Server thread/WARN]: Please see http://www.spigotmc.org/wiki/firewall-guide/ for further information.
[22:13:46] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[22:13:46] [Server thread/INFO]: Preparing level "world"
[22:13:47] [Server thread/ERROR]: Error converting biome key overworld:
java.lang.IllegalArgumentException: Invalid key. Must be [a-z0-9/._-]:
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220) ~[guava-31.1-jre.jar:?]
        at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:86) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:24) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_20_R1.PaperweightFaweAdapter.getRegisteredBiomes(PaperweightFaweAdapter.java:604) ~[FastA>
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.setupBiomes(WorldEditPlugin.java:325) ~[FastAsyncWorldEdit-Bukkit-2.6.5-SNAPSHOT-518.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.setupWorldData(WorldEditPlugin.java:248) ~[FastAsyncWorldEdit-Bukkit-2.6.5-SNAPSHOT-518.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin$WorldInitListener.onWorldInit(WorldEditPlugin.java:650) ~[FastAsyncWorldEdit-Bukkit-2.6.5-SNAP>
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.20.1-R0.1-SNAP>
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2014]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:658) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:611) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2014]

### Minecraft Version

1.20.1

### Iris Version

Iris v2.7.2-1.20.1

### Log

https://mclo.gs/1sYosUs

**Comment by svdgoor** [comment]
@valenvaio the above PR fixes this problem. you can safely update your pack from version 3004 (yours) to this since none of the used values are changed. You can download the pack [here](https://github.com/CocoTheOwner/overworld/archive/refs/heads/no-missing-id-keys.zip)
