### ISSUE TITLE
Pregen catching up for too long...

### ISSUE THREAD

**Issue by FluffyDiscord** [VolmitSoftware/Iris#134]
So, here I am, sitting for 2 hours just to catch up with previous pregen....

Please add some save mechanism, which will remember the last chunk(?) or remember whichh chunks
 were previously generated

![image](https://user-images.githubusercontent.com/10332247/97104105-887f5200-16b1-11eb-9bf4-20c056e5a61a.png)

**Comment by FluffyDiscord** [comment]
here we go, crash

```php
11:05:35 INFO]: [Iris]: Pregen: 25%, Elapsed: 40 minutes, ETA: 2 hours MS: 1,53ms
[11:05:38 ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot invoke "com.volmit.iris.gen.atomics.AtomicWorldData.loadChunk(int, int)" because the return value of "com.volmit.iris.gen.ParallaxTerrainProvider.getParallaxMap()" is null
        at com.volmit.iris.gen.ParallaxTerrainProvider.getParallaxChunk(ParallaxTerrainProvider.java:176) ~[?:?]
        at com.volmit.iris.gen.layer.GenLayerUpdate.populate(GenLayerUpdate.java:48) ~[?:?]
        at net.minecraft.server.v1_16_R2.Chunk.loadCallback(Chunk.java:834) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.PlayerChunk.lambda$null$15(PlayerChunk.java:745) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:149) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1054) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.ChunkProviderServer.runTasks(ChunkProviderServer.java:636) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1144) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-246]
        at java.lang.Thread.run(Unknown Source) [?:?]
[11:05:38 ERROR]: This crash report has been saved to: C:\Users\Mossshine\Desktop\papermc-pregen\.\crash-reports\crash-2020-10-25_11.05.38-server.txt
[11:05:38 INFO]: Stopping server
[11:05:38 INFO]: [Multiverse-Core] Disabling Multiverse-Core v4.2.2-b812
[11:05:38 INFO]: [Iris] Disabling Iris v1.0.25
[11:05:38 INFO]: [Iris]: [Iris]: Unregistered Command /iris
[11:05:38 INFO]: [Iris]: [Iris]: Unregistered Command /iris
[11:05:38 INFO]: [Iris]: [Iris]: Unregistered Command /iris
[11:05:38 INFO]: [Iris]: [Iris]: Unregistered Command /iris
[11:05:38 INFO]: [Iris]: [Iris]: Unregistered Command /iris
[11:05:38 INFO]: [Iris]: [Iris]: Unregistered Command /iris
[11:05:38 INFO]: [Iris]: [Iris]: Unregistered Permission iris.*
[11:05:38 INFO]: [Iris]: [Iris]: Unregistered Permission iris.studio
[11:05:38 INFO]: Saving players
[11:05:38 INFO]: Saving worlds
[11:05:38 INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[11:07:36 INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[11:07:36 INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[11:07:36 INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[11:07:36 INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[11:07:36 INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[11:07:36 INFO]: Saving chunks for level 'ServerLevel[dann]'/minecraft:dann
[11:07:36 INFO]: ThreadedAnvilChunkStorage (dann): All chunks are saved
[11:07:36 INFO]: Saving chunks for level 'ServerLevel[stonks5]'/minecraft:stonks5
[11:07:36 ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "com.volmit.iris.gen.atomics.AtomicWorldData.loadChunk(int, int)" because the return value of "com.volmit.iris.gen.ParallaxTerrainProvider.getParallaxMap()" is null
        at com.volmit.iris.gen.ParallaxTerrainProvider.getParallaxChunk(ParallaxTerrainProvider.java:176) ~[?:?]
        at com.volmit.iris.gen.layer.GenLayerUpdate.populate(GenLayerUpdate.java:48) ~[?:?]
        at net.minecraft.server.v1_16_R2.Chunk.loadCallback(Chunk.java:834) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.PlayerChunk.lambda$null$15(PlayerChunk.java:745) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:149) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1054) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.PlayerChunkMap.lambda$save$24(PlayerChunkMap.java:876) ~[patched_1.16.3.jar:git-Paper-246]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
        at net.minecraft.server.v1_16_R2.PlayerChunkMap.save(PlayerChunkMap.java:882) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.ChunkProviderServer.save(ChunkProviderServer.java:694) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.WorldServer.save(WorldServer.java:999) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.MinecraftServer.saveChunks(MinecraftServer.java:717) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.MinecraftServer.stop(MinecraftServer.java:800) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.DedicatedServer.stop(DedicatedServer.java:698) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1046) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-246]
        at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by svdgoor** [comment]
Closed for not using the proper preset. Please make it again with the preset as that will save us time figuring certain things out.
