### ISSUE TITLE
Bug: Studio Map Broken

### ISSUE THREAD

**Issue by AeternumStudios** [VolmitSoftware/Iris#18]
```
[23:02:53 INFO]: ArchDukeAeternum issued server command: /iris std map
[23:02:53 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'iris' in plugin Iris v1.0.16
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.3.jar:git-Paper-232]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.3.jar:git-Paper-232]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1918) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1729) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-232]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
        at com.volmit.iris.command.CommandIrisStudioMap.handle(CommandIrisStudioMap.java:35) ~[?:?]
        at com.volmit.iris.util.VirtualCommand.hit(VirtualCommand.java:90) ~[?:?]
        at com.volmit.iris.util.VirtualCommand.hit(VirtualCommand.java:105) ~[?:?]
        at com.volmit.iris.util.VirtualCommand.hit(VirtualCommand.java:105) ~[?:?]
        at com.volmit.iris.util.MortarPlugin.onCommand(MortarPlugin.java:493) ~[?:?]
        at com.volmit.iris.Iris.onCommand(Iris.java:261) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.3.jar:git-Paper-232]
        ... 18 more
>
```
Pregened a world, then ran `/iris std map`
v1.0.16

**Comment by AvianAeternum** [comment]
Now on version 1.0.19
```
[06:54:46 INFO]: ArchDukeAeternum issued server command: /iris std map
[06:54:46 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'iris' in plugin Iris v1.0.19
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.3.jar:git-Paper-232]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.3.jar:git-Paper-232]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1918) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1729) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1202) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-232]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
        at com.volmit.iris.command.CommandIrisStudioMap.handle(CommandIrisStudioMap.java:35) ~[?:?]
        at com.volmit.iris.util.VirtualCommand.hit(VirtualCommand.java:90) ~[?:?]
        at com.volmit.iris.util.VirtualCommand.hit(VirtualCommand.java:105) ~[?:?]
        at com.volmit.iris.util.VirtualCommand.hit(VirtualCommand.java:105) ~[?:?]
        at com.volmit.iris.util.MortarPlugin.onCommand(MortarPlugin.java:493) ~[?:?]
        at com.volmit.iris.Iris.onCommand(Iris.java:261) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.3.jar:git-Paper-232]
        ... 18 more
```

**Comment by xCykrix** [comment]
v1.0.21

```
[05:07:42 INFO]: xCykrix issued server command: /iris studio map
[05:07:42 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'iris' in plugin Iris v1.0.21
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.3.jar:git-Paper-216]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.3.jar:git-Paper-216]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.3.jar:git-Paper-216]
        at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1908) ~[patched_1.16.3.jar:git-Paper-216]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1719) ~[patched_1.16.3.jar:git-Paper-216]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.3.jar:git-Paper-216]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.3.jar:git-Paper-216]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-216]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-216]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-216]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-216]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-216]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-216]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-216]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.3.jar:git-Paper-216]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1264) ~[patched_1.16.3.jar:git-Paper-216]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-216]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-216]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at com.volmit.iris.command.CommandIrisStudioMap.handle(CommandIrisStudioMap.java:35) ~[?:?]
        at com.volmit.iris.util.VirtualCommand.hit(VirtualCommand.java:90) ~[?:?]
        at com.volmit.iris.util.VirtualCommand.hit(VirtualCommand.java:105) ~[?:?]
        at com.volmit.iris.util.VirtualCommand.hit(VirtualCommand.java:105) ~[?:?]
        at com.volmit.iris.util.MortarPlugin.onCommand(MortarPlugin.java:493) ~[?:?]
        at com.volmit.iris.Iris.onCommand(Iris.java:247) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.3.jar:git-Paper-216]
        ... 18 more
```

**Comment by svdgoor** [comment]
Does not appear to happen on 1.23
Comment if it does for you, and we will re-examine the issue.

**Comment by xCykrix** [comment]
Reappeared in v1.0.25

```
[08:12:18 INFO]: xCykrix issued server command: /iris std map
[08:12:18 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'iris' in plugin Iris v1.0.25
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.3.jar:git-Purpur-802]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.16.3.jar:git-Purpur-802]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1974) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1777) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1203) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1196) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1333) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1006) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.3.jar:git-Purpur-802]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.NullPointerException
        at com.volmit.iris.command.CommandIrisStudioMap.handle(CommandIrisStudioMap.java:35) ~[?:?]
        at com.volmit.iris.util.VirtualCommand.hit(VirtualCommand.java:90) ~[?:?]
        at com.volmit.iris.util.VirtualCommand.hit(VirtualCommand.java:105) ~[?:?]
        at com.volmit.iris.util.VirtualCommand.hit(VirtualCommand.java:105) ~[?:?]
        at com.volmit.iris.util.MortarPlugin.onCommand(MortarPlugin.java:493) ~[?:?]
        at com.volmit.iris.Iris.onCommand(Iris.java:253) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.3.jar:git-Purpur-802]
        ... 18 more
```

EDIT: This is also replicated in latest PaperMC build, exact error line for line.

**Comment by xCykrix** [comment]
I think this may just be incorrect error handling. If I am in an Iris world, that error appears. If I directly open a studio world however the map viewer opens correctly. Is it intended to only work in the studio editor? If so being outside the editor should generate the correct error accordingly.
