### ISSUE TITLE
Goto Broken, not using biomes in the tab complete/working

### ISSUE THREAD

**Issue by NextdoorPsycho** [VolmitSoftware/Iris#198]
[14:25:37 INFO]: Magic_Psycho issued server command: /iris std goto temperate-birch-forest
[14:25:37 INFO]: [Iris]: Couldn't find Object: temperate-birch-forest
[14:25:37 INFO]: [Iris]: Couldn't find Object: temperate-birch-forest
[14:25:37 INFO]: [Iris]: Couldn't find Object: temperate-birch-forest
[14:25:37 INFO]: [Iris]: Couldn't find Object: temperate-birch-forest
[14:25:37 INFO]: [Iris]: Couldn't find Object: temperate-birch-forest
[14:25:37 INFO]: [Iris]: Couldn't find Object: temperate-birch-forest
[14:25:37 WARN]: java.lang.NullPointerException
[14:25:37 WARN]:        at com.volmit.iris.scaffold.engine.IrisAccess.lambda$lookForBiome$1(IrisAccess.java:262)
[14:25:37 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:25:37 WARN]:        at java.lang.Thread.run(Unknown Source)
[14:25:37 WARN]: java.lang.NullPointerException
[14:25:37 WARN]:        at com.volmit.iris.scaffold.engine.IrisAccess.lambda$lookForBiome$1(IrisAccess.java:262)
[14:25:37 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:25:37 WARN]:        at java.lang.Thread.run(Unknown Source)
[14:25:37 WARN]: java.lang.NullPointerException
[14:25:37 WARN]:        at com.volmit.iris.scaffold.engine.IrisAccess.lambda$lookForBiome$1(IrisAccess.java:262)
[14:25:37 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:25:37 WARN]:        at java.lang.Thread.run(Unknown Source)
[14:25:37 WARN]: java.lang.NullPointerException
[14:25:37 WARN]:        at com.volmit.iris.scaffold.engine.IrisAccess.lambda$lookForBiome$1(IrisAccess.java:262)
[14:25:37 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:25:37 WARN]:        at java.lang.Thread.run(Unknown Source)
[14:25:37 WARN]: java.lang.NullPointerException
[14:25:37 WARN]:        at com.volmit.iris.scaffold.engine.IrisAccess.lambda$lookForBiome$1(IrisAccess.java:262)
[14:25:37 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:25:37 WARN]:        at java.lang.Thread.run(Unknown Source)
[14:25:37 WARN]: java.lang.NullPointerException
[14:25:37 WARN]:        at com.volmit.iris.scaffold.engine.IrisAccess.lambda$lookForBiome$1(IrisAccess.java:262)
[14:25:37 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:25:37 WARN]:        at java.lang.Thread.run(Unknown Source)
[14:25:37 WARN]: java.lang.NullPointerException
[14:25:37 WARN]:        at com.volmit.iris.scaffold.engine.IrisAccess.lambda$lookForBiome$1(IrisAccess.java:262)
[14:25:37 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:25:37 WARN]:        at java.lang.Thread.run(Unknown Source)
[14:25:37 WARN]: java.lang.NullPointerException
[14:25:37 WARN]:        at com.volmit.iris.scaffold.engine.IrisAccess.lambda$lookForBiome$1(IrisAccess.java:262)
[14:25:37 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:25:37 WARN]:        at java.lang.Thread.run(Unknown Source)
[14:25:37 WARN]: java.lang.NullPointerException
[14:25:37 WARN]:        at com.volmit.iris.scaffold.engine.IrisAccess.lambda$lookForBiome$1(IrisAccess.java:262)
[14:25:37 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:25:37 WARN]:        at java.lang.Thread.run(Unknown Source)
[14:25:37 WARN]: java.lang.NullPointerException
[14:25:37 WARN]:        at com.volmit.iris.scaffold.engine.IrisAccess.lambda$lookForBiome$1(IrisAccess.java:262)
[14:25:37 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:25:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:25:37 WARN]:        at java.lang.Thread.run(Unknown Source)
>

**To Reproduce**
use the command

**Expected behavior**
works

**Server and Plugin Information's**
 - Installed plugins: Iris
 - Iris Version: Latest as of git repo

its just nor working properly, try it.
its not working with a few biomes, but some are working. like : temperate-birch-forest, is not working for example

**Comment by Swede37** [comment]
I've been getting that error in console too, after I edit a custom biome in studio and it hotloads.  I was just blaming myself for messing up somehow. Using Iris v1.1.4 and paper-1.16.4-298 ( I rolled back from latest paper build thinking it was the culprit).
EDIT:  If I copied the studio biome, dimension, and updated region folders back into the overworld folder - which was used as the template for my studio world - then reloaded & hotloaded -  it would then locate the biome.  So it must not be linking the changes back to overworld?

**Comment by astrsh** [comment]
The goto command should really be split based on whether you're searching for regions/biomes/objects to avoid potential name conflicts, would probably fix this by doing so

Perhaps something like `/iris std goto biome temperate-forest`

**Comment by svdgoor** [comment]
Other issues are currently more strongly affecting usability which leads me to think this is not high priority at the moment. Will likely include in next update cycle

**Comment by svdgoor** [comment]
more info in VolmitSoftware/Iris#208 which is now closed due to being a duplicate.

**Comment by svdgoor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Studio GOTO command](https://trello.com/c/gYn46aVd/9-studio-goto-command)

**Comment by ghost** [comment]
/iris std goto temperate-birch-forest is working on iris 1.3. If it still happens for someone it will be reopend.
