### ISSUE TITLE
Server stopping sporadically, when specific player joins in specific location

### ISSUE THREAD

**Issue by chrismwiggs** [VolmitSoftware/Iris#328]
Getting sudden server crashes when a player enters a specific area (can't tell which). Feels like a corrupt chunk sort of thing where if the player logs on and goes back to the same spot, the server will crash again right away.

This is on Paper 1.16.5, Iris 1.3.2. 

Error: 
```
[13:11:13 ERROR]: Exception stopping the server
java.util.concurrent.CompletionException: net.minecraft.server.v1_16_R3.ReportedException: Exception generating new chunk
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_275]
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_275]
at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:975) ~[?:1.8.0_275]
at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) ~[?:1.8.0_275]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_275]
at net.minecraft.server.v1_16_R3.ChunkTaskQueueSorter.b(SourceFile:58) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.ThreadedMailbox.e(ThreadedMailbox.java:90) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.ThreadedMailbox.a(ThreadedMailbox.java:137) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.ThreadedMailbox.run(ThreadedMailbox.java:102) ~[patched_1.16.5.jar:git-Purpur-982]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: net.minecraft.server.v1_16_R3.ReportedException: Exception generating new chunk
at net.minecraft.server.v1_16_R3.PlayerChunkMap.lambda$b$41(PlayerChunkMap.java:1313) ~[patched_1.16.5.jar:git-Purpur-982]
at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.PlayerChunkMap.lambda$b$43(PlayerChunkMap.java:1298) ~[patched_1.16.5.jar:git-Purpur-982]
at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966) ~[?:1.8.0_275]
... 9 more
Caused by: java.lang.NullPointerException
at com.volmit.iris.generator.IrisEngineCompound.<init>(IrisEngineCompound.java:65) ~[?:?]
at com.volmit.iris.scaffold.engine.EngineCompositeGenerator.initialize(EngineCompositeGenerator.java:292) ~[?:?]
at com.volmit.iris.scaffold.engine.EngineCompositeGenerator.generateChunkRawData(EngineCompositeGenerator.java:492) ~[?:?]
at com.volmit.iris.scaffold.engine.EngineCompositeGenerator.generateChunkData(EngineCompositeGenerator.java:312) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.generator.CustomChunkGenerator.buildBase(CustomChunkGenerator.java:112) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.ChunkStatus.lambda$static$6(ChunkStatus.java:55) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.ChunkStatus$d.doWork(ChunkStatus.java:249) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.ChunkStatus.a(ChunkStatus.java:193) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.PlayerChunkMap.lambda$b$41(PlayerChunkMap.java:1300) ~[patched_1.16.5.jar:git-Purpur-982]
at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.PlayerChunkMap.lambda$b$43(PlayerChunkMap.java:1298) ~[patched_1.16.5.jar:git-Purpur-982]
at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966) ~[?:1.8.0_275]
```

**Comment by stijnb1234** [comment]
Related to this:
https://github.com/VolmitSoftware/Iris/blob/4cfdc5bf306c3590baa0b87ce7e48abb37a6a3b3/src/main/java/com/volmit/iris/generator/IrisEngineCompound.java#L65

So the IrisDimension is null? 🤔

**Comment by svdgoor** [comment]
No the Composite is null.
IrisDimensions can be stacked using Composite dimensions, but that system seems to have been somewhat rushed in development and sometimes the composite is attempted to be gotten when it is not actually used/set (is null). Should be resolvable with a if composite != null.

**Comment by ghost** [comment]
@chrismwiggs was a pregen running while players were exploring the world?

**Comment by chrismwiggs** [comment]
Not a pregen, but generating on the fly. This now also is happening when trying to pregen; fully unable to generate new chunks without crashing every 5-10 minutes.

**Comment by ghost** [comment]
> Not a pregen, but generating on the fly. This now also is happening when trying to pregen; fully unable to generate new chunks without crashing every 5-10 minutes.

Can you provide this info pls
**Server and Plugin Informations**
 - Installed plugins:
 - Iris Version:
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]:
 - Operating System (if applicable):
 - Server Logs:

**Comment by chrismwiggs** [comment]
Most of that I've provided already (although I don't know why the OS would matter, but it's Ubuntu 20.04)

 It sounds like coco already knows what the issue is though, we're just waiting for the build server to be fixed.

**Comment by ghost** [comment]
Oh_the_dungeons_youll_go did cause a lot of problems in the past. can you try disable that plugin and run the server?

**Comment by chrismwiggs** [comment]
Same error happening

**Comment by chrismwiggs** [comment]
So did some painful troubleshooting and found some more info out here. I've been using Iris for the past 3 weeks with no problems at all, until this started 3 ish days ago. Turns out it started almost exactly after the server crashed from a different issue.

For the sake of trying everything, I decided to remove the Iris folder in my world's folder and give it a go, and lo and behold, it worked. New chunks gen properly, pregenning is working, everything seems ok. 

If I had to guess, the crash did something to whatever the files in this folder are for because they're in memory (I didn't really investigate too deeply what they are, but I assume you know, or at least I hope!)? Worries me that these files are important (otherwise, why are they here) and that a simple crash can cause issues with them moving forward. What is stored here?

I still have the folder if sending it to someone would be helpful!

**Comment by svdgoor** [comment]
@chrismwiggs Could you upload that to some cloud storage and paste a link here please?

**Comment by svdgoor** [comment]
Ded thread. If still occuring on latest, mention on a new bug report.

**Comment by NextdoorPsycho** [comment]
Fixed on latest with composits breaking bounds (like4.5 i think
