### ISSUE TITLE
NPE that halts Jigsaw editing permanently 

### ISSUE THREAD

**Issue by StrangeOne101** [VolmitSoftware/Iris#377]
**Describe the bug**
Using `/iris jigsaw create` but typing an object that doesn't exist will cause the following NPE, which will then stop any jigsaw pieces from being created, edited or saved. A server restart has to occur to fix it. Very annoying bug when doing jigsaw stuff as you have to restart EVERY time you mistype a command

NPE:
```
Caused by: java.lang.NullPointerException
        at com.volmit.iris.manager.edit.JigsawEditor.<init>(JigsawEditor.java:49) ~[?:?]
        at com.volmit.iris.manager.command.jigsaw.CommandIrisJigsawNew.handle(CommandIrisJigsawNew.java:52) ~[?:?]
        at com.volmit.iris.util.VirtualCommand.hit(VirtualCommand.java:126) ~[?:?]
        at com.volmit.iris.util.VirtualCommand.hit(VirtualCommand.java:108) ~[?:?]
        at com.volmit.iris.util.VirtualCommand.hit(VirtualCommand.java:108) ~[?:?]
        at com.volmit.iris.util.VolmitPlugin.onCommand(VolmitPlugin.java:639) ~[?:?]
        at com.volmit.iris.Iris.onCommand(Iris.java:289) ~[?:?]
```

**To Reproduce**
1. Type `/iris jigsaw create a overworld a`
2. See NPE
3. See how jigsaw commands are now completely broken and unusable 

**Server and Plugin Informations**
 - Iris Version: 1.3.10 (9b4384d3e6fd92f91a9e18d0ba4e7c55962d65b1)
 - Purpur 1.16.5-1169
 - Operating System: Win10

**Comment by StrangeOne101** [comment]
Fixed and merged with b6bc269
