### ISSUE TITLE
Jigsaw Rotation NPE on Place

### ISSUE THREAD

**Issue by StrangeOne101** [VolmitSoftware/Iris#381]
**Describe the bug**
Unsure why this occurs, but this NPE sometimes occurs when placing Jigsaws. Cannot figure out the issue in the code either, so I'm making a GitHub issue so this doesn't get forgotten about overnight by myself (or others)

```Caused by: java.lang.NullPointerException
        at io.timeandspace.smoothie.Utils.checkNonNull(Utils.java:75) ~[?:?]
        at io.timeandspace.smoothie.SmoothieMap.put(SmoothieMap.java:1462) ~[?:?]
        at com.volmit.iris.object.IrisObject.rotate(IrisObject.java:853) ~[?:?]
        at com.volmit.iris.object.IrisObject.rotateCopy(IrisObject.java:839) ~[?:?]
        at com.volmit.iris.object.IrisObjectRotation.rotateCopy(IrisObjectRotation.java:58) ~[?:?]
        at com.volmit.iris.scaffold.jigsaw.PlannedStructure.rotated(PlannedStructure.java:430) ~[?:?]
        at com.volmit.iris.scaffold.jigsaw.PlannedPiece.<init>(PlannedPiece.java:42) ~[?:?]
        at com.volmit.iris.scaffold.jigsaw.PlannedStructure.generateRotatedPiece(PlannedStructure.java:249) ~[?:?]
        at com.volmit.iris.scaffold.jigsaw.PlannedStructure.generateRotatedPiece(PlannedStructure.java:227) ~[?:?]
        at com.volmit.iris.scaffold.jigsaw.PlannedStructure.generateConnectorOutwards(PlannedStructure.java:208) ~[?:?]
        at com.volmit.iris.scaffold.jigsaw.PlannedStructure.generatePieceOutwards(PlannedStructure.java:196) ~[?:?]
        at com.volmit.iris.scaffold.jigsaw.PlannedStructure.generateOutwards(PlannedStructure.java:184) ~[?:?]
        at com.volmit.iris.scaffold.jigsaw.PlannedStructure.<init>(PlannedStructure.java:44) ~[?:?]
        at com.volmit.iris.manager.command.jigsaw.CommandIrisJigsawPlace.handle(CommandIrisJigsawPlace.java:51) ~[?:?]
```

**Server and Plugin Informations**
 - Iris Version: v1.3.10
 - Server Platform and Version: Purpur-1.16.5-1139
 - Operating System (if applicable): Win10

**Comment by StrangeOne101** [comment]
Fixed in v1.3.10-FINAL
