### ISSUE TITLE
Spam in regards to objects from "V1" objects

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#444]
[22:10:25 INFO]: [Iris]: Exception Logged: IOException: Not V2 Format
[22:10:25 INFO]: [Iris]: Exception Logged: EOFException: null

This is only in exceptionloggin btw.

**Comment by svdgoor** [comment]
Exception Logged: IllegalArgumentException: Data not created via string parsing
Guessing this is related

**Comment by svdgoor** [comment]
https://github.com/VolmitSoftware/Iris/issues/447#issuecomment-883717136

**Comment by svdgoor** [comment]
```
Thread: Iris Engine Overworld 4
First: Tue Jul 20 23:36:48 CEST 2021
java.lang.IllegalArgumentException: Data not created via string parsing
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.merge(CraftBlockData.java:103)
	at com.volmit.iris.engine.object.IrisObject.place(IrisObject.java:622)
	at com.volmit.iris.engine.framework.EngineParallaxManager.place(EngineParallaxManager.java:586)
	at com.volmit.iris.engine.framework.EngineParallaxManager.place(EngineParallaxManager.java:540)
	at com.volmit.iris.engine.framework.EngineParallaxManager.generateParallaxSurface(EngineParallaxManager.java:479)
	at com.volmit.iris.engine.framework.EngineParallaxManager.generateParallaxLayer(EngineParallaxManager.java:365)
	at com.volmit.iris.engine.framework.EngineParallaxManager.generateParallaxLayer(EngineParallaxManager.java:390)
	at com.volmit.iris.engine.framework.EngineParallaxManager.lambda$generateParallaxArea$10(EngineParallaxManager.java:316)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
	```
The debug logger caught this

**Comment by svdgoor** [comment]
Perhaps an object converter to convert V1 objects to V2 (?) objects to fix this, and most other object placement "errors" (more like warnings) #450 #446

**Comment by cyberpwnn** [comment]
Turn off Debug mode, it's not for you :P

**Comment by svdgoor** [comment]
Ok then.
