### ISSUE TITLE
Iris complaining on first startup that compat.json is missing

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#502]
Iris is complaining that its missing a file that iris will generate on first startup. So Iris just being dumb. 

Error log:
```
[15:48:22 WARN]: java.io.FileNotFoundException: plugins\Iris\compat.json (Das System kann die angegebene Datei nicht finden)
[15:48:22 WARN]:        at java.base/java.io.FileInputStream.open0(Native Method)
[15:48:22 WARN]:        at java.base/java.io.FileInputStream.open(FileInputStream.java:211)
[15:48:22 WARN]:        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:153)
[15:48:22 WARN]:        at java.base/java.io.FileReader.<init>(FileReader.java:75)
[15:48:22 WARN]:        at Iris-1.6.3.jar//com.volmit.iris.util.io.IO.readAll(IO.java:345)
[15:48:22 WARN]:        at Iris-1.6.3.jar//com.volmit.iris.engine.object.compat.IrisCompat.configured(IrisCompat.java:162)
[15:48:22 WARN]:        at Iris-1.6.3.jar//com.volmit.iris.Iris.onEnable(Iris.java:119)
[15:48:22 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[15:48:22 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[15:48:22 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[15:48:22 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:529)
[15:48:22 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:443)
[15:48:22 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:287)
[15:48:22 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1201)
[15:48:22 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[15:48:22 WARN]:        at net.minecraft.server.MinecraftServer$$Lambda$3730/0x000000001a354618.run(Unknown Source)
[15:48:22 WARN]:        at java.base/java.lang.Thread.run(Thread.java:853)
```

**Comment by svdgoor** [comment]
#510

**Comment by svdgoor** [comment]
Patched on upcoming version
