### ISSUE TITLE
/iris what objects - Unhandled exception executing command 'iris' in plugin Iris v1.7

### ISSUE THREAD

**Issue by jaysonsperling** [VolmitSoftware/Iris#533]
### Problem

- Iris version: 1.7 (downloaded from Spigot 8/13/2021 1:12PM MT and dropped in as a replacement for 1.6.7)
- Server version: Paper version git-Paper-170 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 80650e8)
- Plugins: AsyncWorldEdit, ClearLag, CoreProtect, Essentials, EssentialsSpawn, Iris, LuckPerms, Multiverse-Core, MythicMobs, PlaceholderAPI, ProtocolLib, Vault, WorldEdit, WorldEditSUI
- OS: Mac OS Mojave 10.14.6
- Java: java version "16.0.2" 2021-07-20 | Java(TM) SE Runtime Environment (build 16.0.2+7-67) | Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)
---
Reproduce:
/iris studio open MPKCraft (based off of the example template)
/irish what objects
Console shows error indicated in https://gist.github.com/jaysonsperling/3205861ba961b4fd4b61b0e09234264e:
```
[13:32:55 INFO]: JaysonBond issued server command: /iris what objects
[13:32:55 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'iris' in plugin Iris v1.7
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Paper-170]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-170]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:832) ~[patched_1.17.1.jar:git-Paper-170]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2170) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1981) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1962) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-170]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[patched_1.17.1.jar:git-Paper-170]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Paper-170]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[patched_1.17.1.jar:git-Paper-170]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[patched_1.17.1.jar:git-Paper-170]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1281) ~[patched_1.17.1.jar:git-Paper-170]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[patched_1.17.1.jar:git-Paper-170]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-170]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.io.File.getName()" because the return value of "com.volmit.iris.engine.object.biome.IrisBiome.getLoadFile()" is null
        at com.volmit.iris.core.command.what.CommandIrisWhatObjects.handle(CommandIrisWhatObjects.java:145) ~[Iris-1.7.jar:?]
        at com.volmit.iris.util.plugin.VirtualCommand.hit(VirtualCommand.java:98) ~[Iris-1.7.jar:?]
        at com.volmit.iris.util.plugin.VirtualCommand.hit(VirtualCommand.java:110) ~[Iris-1.7.jar:?]
        at com.volmit.iris.util.plugin.VirtualCommand.hit(VirtualCommand.java:110) ~[Iris-1.7.jar:?]
        at com.volmit.iris.util.plugin.VolmitPlugin.onCommand(VolmitPlugin.java:550) ~[Iris-1.7.jar:?]
        at com.volmit.iris.Iris.onCommand(Iris.java:434) ~[Iris-1.7.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-170]
        ... 21 more
>
```

### Minecraft Version

1.17.x

### Iris Version

1.7

### Log

https://gist.github.com/jaysonsperling/3205861ba961b4fd4b61b0e09234264e

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by ghost** [comment]
Couldnt be reproduced on the latest version 1.7.7 so this can be closed @CocoTheOwner
