### ISSUE TITLE
Mantle Error

### ISSUE THREAD

**Issue by jaysonsperling** [VolmitSoftware/Iris#534]
### Problem

- Iris version: 1.7 (downloaded from Spigot 8/13/2021 1:12PM MT and dropped in as a replacement for 1.6.7)
- Server version: Paper version git-Paper-170 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 80650e8)
- Plugins: AsyncWorldEdit, ClearLag, CoreProtect, Essentials, EssentialsSpawn, Iris, LuckPerms, Multiverse-Core, MythicMobs, PlaceholderAPI, ProtocolLib, Vault, WorldEdit, WorldEditSUI
- OS: Mac OS Mojave 10.14.6 Java: java version "16.0.2" 2021-07-20 | Java(TM) SE Runtime Environment (build 16.0.2+7-67) | Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)

---

I made a change to my config (indicated below) to attempt to get loot to work with an Iris object and the studio triggered a reload and then I started to fly and the following error popped up and the server stopped execution and died.

Config:
```
"objects": [
        {
            "chance": 0.1,
            "density": 3,
            "place": [
                "clutter/literalgarbage1"
            ],
            "loot": [
                {
                    "name": "test-beach-treasure",
                    "exact": false,
                    "filter": [
                        {
                            "block": "minecraft:chest",
                            "debug": true
                        }
                    ],
                    "weight": 1
                }
            ]
        },
```

Error:
```
[13:44:41 INFO]: [Iris]: engine/platform/BukkitChunkGenerator 117 Generated 11 -129
[13:44:41 INFO]: [Iris]: engine/platform/BukkitChunkGenerator 117 Generated 12 -129
[13:44:41 INFO]: [Iris]: engine/platform/BukkitChunkGenerator 117 Generated -2 -128
[13:44:41 ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: The Mantle is closed
        at com.volmit.iris.util.mantle.Mantle.get(Mantle.java:170) ~[Iris-1.7.jar:?]
        at com.volmit.iris.engine.framework.Engine.getObjectPlacement(Engine.java:639) ~[Iris-1.7.jar:?]
        at com.volmit.iris.engine.framework.Engine.getLootTables(Engine.java:347) ~[Iris-1.7.jar:?]
        at com.volmit.iris.engine.framework.Engine.update(Engine.java:280) ~[Iris-1.7.jar:?]
        at com.volmit.iris.engine.framework.Engine.lambda$updateChunk$0(Engine.java:240) ~[Iris-1.7.jar:?]
        at com.volmit.iris.util.mantle.MantleChunk.lambda$iterate$0(MantleChunk.java:196) ~[Iris-1.7.jar:?]
        at com.volmit.iris.util.hunk.storage.MappedHunk.iterateSync(MappedHunk.java:76) ~[Iris-1.7.jar:?]
        at com.volmit.iris.util.mantle.MantleChunk.iterate(MantleChunk.java:196) ~[Iris-1.7.jar:?]
        at com.volmit.iris.util.mantle.Mantle.iterateChunk(Mantle.java:111) ~[Iris-1.7.jar:?]
        at com.volmit.iris.engine.framework.Engine.updateChunk(Engine.java:236) ~[Iris-1.7.jar:?]
        at com.volmit.iris.engine.IrisEngine.populate(IrisEngine.java:418) ~[Iris-1.7.jar:?]
        at net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:838) ~[app:?]
        at net.minecraft.server.level.ChunkHolder.lambda$updateFutures$22(ChunkHolder.java:793) ~[app:?]
        at net.minecraft.server.level.ChunkMap$CallbackExecutor.run(ChunkMap.java:210) ~[app:?]
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1084) ~[app:?]
        at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:667) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1336) ~[patched_1.17.1.jar:git-Paper-170]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[patched_1.17.1.jar:git-Paper-170]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1281) ~[patched_1.17.1.jar:git-Paper-170]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[patched_1.17.1.jar:git-Paper-170]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-170]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[13:44:41 INFO]: [Iris]: engine/platform/BukkitChunkGenerator 117 Generated 13 -129
```

### Minecraft Version

1.17.x

### Iris Version

1.7

### Log

https://gist.github.com/jaysonsperling/17b10c33dc5db85e4f809efeb0d9024f

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by ghost** [comment]
@jaysonsperling still a problem on 1.7.7 or is this fixed? If so you can close this report

**Comment by svdgoor** [comment]
Hotloading with the mantle enabled was probably broken in 1.7, considering the recent mantle & hotloading updates I assume this is resolved. Let us know when not.
