### ISSUE TITLE
Iris worlds cannot be loaded

### ISSUE THREAD

**Issue by StrangeOne101** [VolmitSoftware/Iris#543]
### Problem

Iris worlds cannot be loaded at all.

When they are loaded, a stacktrace occurs. Note this was loaded with Multiverse because of issue #542

```[22:07:09] [Server thread/INFO]: CONSOLE: Starting import of world 'newworld2'...
[22:07:09] [Server thread/INFO]: [Iris]: Generator ID: overworld requested by bukkit/plugin. Assuming IrisDimension: overworld
[22:07:10] [Server thread/WARN]: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Cannot find dimension in D:\Servers\1.17 Test Server\newworld2\iris with key overworld
[22:07:10] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
[22:07:10] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2069)
[22:07:10] [Server thread/WARN]: 	at com.volmit.iris.engine.platform.EngineProvider.getEngine(EngineProvider.java:61)
[22:07:10] [Server thread/WARN]: 	at com.volmit.iris.engine.platform.BukkitChunkGenerator.getEngine(BukkitChunkGenerator.java:82)
[22:07:10] [Server thread/WARN]: 	at com.volmit.iris.engine.platform.PlatformChunkGenerator.getTarget(PlatformChunkGenerator.java:38)
[22:07:10] [Server thread/WARN]: 	at com.volmit.iris.engine.platform.BukkitChunkGenerator.<init>(BukkitChunkGenerator.java:78)
[22:07:10] [Server thread/WARN]: 	at com.volmit.iris.Iris.getDefaultWorldGenerator(Iris.java:477)
[22:07:10] [Server thread/WARN]: 	at org.bukkit.WorldCreator.getGeneratorForName(WorldCreator.java:436)
[22:07:10] [Server thread/WARN]: 	at org.bukkit.WorldCreator.generator(WorldCreator.java:263)
[22:07:10] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:260)
[22:07:10] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.commands.ImportCommand.runCommand
```

### Solution

GLHF

### Minecraft Version

1.17.x

### Iris Version

1.7 @ 30c5a0d

### Log

https://pastebin.com/8kbJ9kEH

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by svdgoor** [comment]
dupe of #532

**Comment by StrangeOne101** [comment]
Ah what a noob (me). I'll close
