### ISSUE TITLE
iris create command error

### ISSUE THREAD

**Issue by xair0** [VolmitSoftware/Iris#560]
### Problem

> iris create survival normal
[13:09:20 WARN]: com.volmit.iris.util.exceptions.IrisException: Dimension cannot be found null for id overworld
[13:09:20 WARN]:        at Iris-1.7.3.jar//com.volmit.iris.core.tools.IrisCreator.create(IrisCreator.java:97)
[13:09:20 WARN]:        at Iris-1.7.3.jar//com.volmit.iris.core.command.world.CommandIrisCreate.lambda$handle$0(CommandIrisCreate.java:131)
[13:09:20 WARN]:        at Iris-1.7.3.jar//com.volmit.iris.util.scheduling.J.lambda$a$1(J.java:77)
[13:09:20 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[13:09:20 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[13:09:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

### Minecraft Version

1.17.x

### Iris Version

1.17.1

### Log

logs in description

### Checklist

- [x] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by svdgoor** [comment]
Already patched on master branch.
Thanks for reporting, please wait for the plugin to be updated or try this tutorial created by Vitae:
https://youtu.be/jmcE0c4TbVw to get the plugin already
