### ISSUE TITLE
pregenerator doesnt work after server restart

### ISSUE THREAD

**Issue by TheHappyHopper** [VolmitSoftware/Iris#575]
iris version 1.7.7
using bukkit.yml generator
worlds: 
  world: 
    generator: Iris:overworld

[14:04:30 WARN]: [Iris] Task #1212 for Iris v1.7.7 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getLoadedChunks()" because "this.world" is null
	at com.volmit.iris.core.pregenerator.methods.AsyncPregenMethod.lambda$unloadAndSaveAllChunks$0(AsyncPregenMethod.java:52) ~[Iris-1.7.7.jar:?]
	at com.volmit.iris.util.scheduling.J.lambda$sfut$4(J.java:219) ~[Iris-1.7.7.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1331]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1331]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1565) ~[patched_1.17.1.jar:git-Purpur-1331]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[patched_1.17.1.jar:git-Purpur-1331]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Purpur-1331]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-Purpur-1331]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1331]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by ghost** [comment]
Cant replicate this with either 1.7.7 or 1.7.8 so this can be closed @NextdoorPsycho 
Also next time use the correct formular for a report otherwise we are limited to replicate your issue

**Comment by cyberpwnn** [comment]
Format is fine, the template is for people who dont know what information is relevant.

**Comment by Classicalad** [comment]
Didn’t want to create a replica issue, but i have this exact same issue. I’m on iris .9, most recent pur pur as of this morning, and I deleted all Iris world/plug-in folders when trying on pur pur with the new jar. 

Sorry if this is the wrong place.

**Comment by ghost** [comment]
> Didn’t want to create a replica issue, but i have this exact same issue. I’m on iris .9, most recent pur pur as of this morning, and I deleted all Iris world/plug-in folders when trying on pur pur with the new jar.
> 
> Sorry if this is the wrong place.

Does that issue occur on your local pc or on a docker? If it’s on a docker than it’s due to your host

**Comment by Classicalad** [comment]
Thanks for the response. Yeah, I set up my server environment on localhost, you're completely right, there were no issues. Damn that's really frustrating. I'm using an OVH VPS as my host as well, 4 vcores and 16gb memory. It's always been perfect for everything I've tried doing to it.

Do you have any suggestions as to what could be wrong with my host that could cause that issue? Thanks again for the response.

**Comment by TheHappyHopper** [comment]
i still get this issue on latest everything on local pc

**Comment by ghost** [comment]
We cant reproduce it so we cant fix it. We need proper steps of the reproduction. I tried to trigger it multiple times and couldnt get it.

**Comment by TheHappyHopper** [comment]
nevermind i was on discord with the owner last night and we fixed it there
