### ISSUE TITLE
java.util.ConcurrentModificationException: null

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#580]
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
        at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
        at com.volmit.iris.engine.IrisWorldManager.getCooldown(IrisWorldManager.java:344) ~[Iris-1.7.10.jar:?]
        at com.volmit.iris.engine.IrisWorldManager.canSpawn(IrisWorldManager.java:337) ~[Iris-1.7.10.jar:?]
        at com.volmit.iris.engine.IrisWorldManager$$Lambda$5480/0x000000001f522940.test(Unknown Source) ~[Iris-1.7.10.jar:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487) ~[?:?]
        at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312) ~[?:?]
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:739) ~[?:?]
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:740) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at com.volmit.iris.engine.IrisWorldManager.spawnIn(IrisWorldManager.java:253) ~[Iris-1.7.10.jar:?]
        at com.volmit.iris.engine.IrisWorldManager.lambda$onChunkLoad$9(IrisWorldManager.java:373) ~[Iris-1.7.10.jar:?]
        at com.volmit.iris.engine.IrisWorldManager$$Lambda$5248/0x000000001f4a7ba8.run(Unknown Source) ~[Iris-1.7.10.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1339]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [patched_1.17.1.jar:git-Purpur-1339]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.17.1.jar:git-Purpur-1339]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:853) [?:?]

Running Iris 1.7.10 on normal start

**Comment by ghost** [comment]
Still happens on Iris 1.8

**Comment by ghost** [comment]
Haven’t seen this in a long time so I close this. This wasn’t a really issue. Properly just a warning
