### ISSUE TITLE
Mantle Errors

### ISSUE THREAD

**Issue by StrangeOne101** [VolmitSoftware/Iris#609]
### Problem

```
[23:01:14 WARN]: java.util.concurrent.ExecutionException: java.lang.IllegalMonitorStateException
[23:01:14 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1011)
[23:01:14 WARN]:        at com.volmit.iris.util.mantle.Mantle.get(Mantle.java:366)
[23:01:14 WARN]:        at com.volmit.iris.util.mantle.Mantle.getChunk(Mantle.java:133)
[23:01:14 WARN]:        at com.volmit.iris.engine.mantle.MantleWriter.<init>(MantleWriter.java:63)
[23:01:14 WARN]:        at com.volmit.iris.util.mantle.Mantle.write(Mantle.java:112)
[23:01:14 WARN]:        at com.volmit.iris.engine.mantle.EngineMantle.generateMatter(EngineMantle.java:205)
[23:01:14 WARN]:        at com.volmit.iris.engine.IrisEngine.generate(IrisEngine.java:427)
[23:01:14 WARN]:        at com.volmit.iris.engine.platform.BukkitChunkGenerator.generateChunkData(BukkitChunkGenerator.java:296)
[23:01:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.generator.CustomChunkGenerator.buildBase(CustomChunkGenerator.java:119)
[23:01:14 WARN]:        at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$7(ChunkStatus.java:77)
[23:01:14 WARN]:        at net.minecraft.world.level.chunk.ChunkStatus$d.doWork(ChunkStatus.java:276)
[23:01:14 WARN]:        at net.minecraft.world.level.chunk.ChunkStatus.a(ChunkStatus.java:212)
[23:01:14 WARN]:        at net.minecraft.server.level.PlayerChunkMap.lambda$scheduleChunkGeneration$38(PlayerChunkMap.java:1365)
[23:01:14 WARN]:        at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[23:01:14 WARN]:        at net.minecraft.server.level.PlayerChunkMap.lambda$scheduleChunkGeneration$40(PlayerChunkMap.java:1363)
[23:01:14 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
[23:01:14 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[23:01:14 WARN]:        at net.minecraft.server.level.ChunkTaskQueueSorter.lambda$message$1(ChunkTaskQueueSorter.java:58)
[23:01:14 WARN]:        at net.minecraft.util.thread.ThreadedMailbox.g(ThreadedMailbox.java:87)
[23:01:14 WARN]:        at net.minecraft.util.thread.ThreadedMailbox.a(ThreadedMailbox.java:141)
[23:01:14 WARN]:        at net.minecraft.util.thread.ThreadedMailbox.run(ThreadedMailbox.java:96)
[23:01:14 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[23:01:14 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[23:01:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

### Minecraft Version

1.17.x

### Iris Version

1.8.3

### Log

https://pastebin.com/Cagz87Bg

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](https://discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](https://discord.gg/volmit))

**Comment by svdgoor** [comment]
Have not seen on latest
