### ISSUE TITLE
Async Mob Issue

### ISSUE THREAD

**Issue by StrangeOne101** [VolmitSoftware/Iris#613]
### Problem

```
[10:34:55 WARN]: java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
[10:34:55 WARN]:     at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
[10:34:55 WARN]:     at net.minecraft.server.level.WorldServer.getEntities(WorldServer.java:1757)
[10:34:55 WARN]:     at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getEntities(CraftWorld.java:1005)
[10:34:55 WARN]:     at org.bukkit.craftbukkit.v1_17_R1.CraftChunk.getEntities(CraftChunk.java:113)
[10:34:55 WARN]:     at com.volmit.iris.engine.IrisWorldManager.spawnIn(IrisWorldManager.java:270)
[10:34:55 WARN]:     at com.volmit.iris.engine.IrisWorldManager.onAsyncTick(IrisWorldManager.java:225)
[10:34:55 WARN]:     at com.volmit.iris.engine.IrisWorldManager$1.loop(IrisWorldManager.java:143)
[10:34:55 WARN]:     at com.volmit.iris.util.scheduling.Looper.run(Looper.java:30)
```

### Minecraft Version

1.17.1

### Iris Version

1.8.5

### Log

.

**Comment by cyberpwnn** [comment]
Need a new stack trace if you can reproduce this @StrangeOne101

**Comment by svdgoor** [comment]
https://hastebin.com/uzevohucet.yaml

**Comment by svdgoor** [comment]
Believe this is no longer happening on latest.
