### ISSUE TITLE
Exiting Studio worlds causes errors

### ISSUE THREAD

**Issue by StrangeOne101** [VolmitSoftware/Iris#642]
### Problem

```
[01:32:21] [Server thread/INFO]: StrangeOne101 issued server command: /iris std x
[01:32:21] [Server thread/WARN]: [Multiverse-Core] Hmm Multiverse does not know about this world but it's loaded in memory.
[01:32:21] [Server thread/WARN]: [Multiverse-Core] To let Multiverse know about it, use:
[01:32:21] [Server thread/WARN]: [Multiverse-Core] /mv import iris/411f2c2f-5463-4595-8279-bd0da25f7d89 NORMAL
[01:32:22] [Worker-Main-6/INFO]: [Iris]: Failed to generate -4464, 208
[01:32:22] [Worker-Main-6/WARN]: java.util.ConcurrentModificationException
[01:32:22] [Worker-Main-6/WARN]: 	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
[01:32:22] [Worker-Main-6/WARN]: 	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
[01:32:22] [Worker-Main-6/WARN]: 	at com.volmit.iris.engine.IrisEngine.generate(IrisEngine.java:477)
[01:32:22] [Worker-Main-6/WARN]: 	at com.volmit.iris.engine.platform.BukkitChunkGenerator.generateChunkData(BukkitChunkGenerator.java:288)
[01:32:22] [Worker-Main-6/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.generator.CustomChunkGenerator.buildBase(CustomChunkGenerator.java:119)
[01:32:22] [Worker-Main-6/WARN]: 	at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$7(ChunkStatus.java:77)
[01:32:22] [Worker-Main-6/WARN]: 	at net.minecraft.world.level.chunk.ChunkStatus$d.doWork(ChunkStatus.java:276)
[01:32:22] [Worker-Main-6/WARN]: 	at net.minecraft.world.level.chunk.ChunkStatus.a(ChunkStatus.java:212)
[01:32:22] [Worker-Main-6/WARN]: 	at net.minecraft.server.level.PlayerChunkMap.lambda$scheduleChunkGeneration$38(PlayerChunkMap.java:1365)
[01:32:22] [Worker-Main-6/WARN]: 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[01:32:22] [Worker-Main-6/WARN]: 	at net.minecraft.server.level.PlayerChunkMap.lambda$scheduleChunkGeneration$40(PlayerChunkMap.java:1363)
[01:32:22] [Worker-Main-6/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
[01:32:22] [Worker-Main-6/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[01:32:22] [Worker-Main-6/WARN]: 	at net.minecraft.server.level.ChunkTaskQueueSorter.lambda$message$1(ChunkTaskQueueSorter.java:58)
[01:32:22] [Worker-Main-6/WARN]: 	at net.minecraft.util.thread.ThreadedMailbox.g(ThreadedMailbox.java:87)
[01:32:22] [Worker-Main-6/WARN]: 	at net.minecraft.util.thread.ThreadedMailbox.a(ThreadedMailbox.java:141)
[01:32:22] [Worker-Main-6/WARN]: 	at net.minecraft.util.thread.ThreadedMailbox.run(ThreadedMailbox.java:96)
[01:32:22] [Worker-Main-6/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[01:32:22] [Worker-Main-6/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[01:32:22] [Worker-Main-6/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[01:32:25] [Worker-Main-5/INFO]: [Iris]: ======================================
[01:32:25] [Worker-Main-5/WARN]: com.volmit.iris.engine.framework.WrongEngineBroException
[01:32:25] [Worker-Main-5/WARN]: 	at com.volmit.iris.engine.IrisEngine.generate(IrisEngine.java:461)
[01:32:25] [Worker-Main-5/WARN]: 	at com.volmit.iris.engine.platform.BukkitChunkGenerator.generateChunkData(BukkitChunkGenerator.java:288)
[01:32:25] [Worker-Main-5/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.generator.CustomChunkGenerator.buildBase(CustomChunkGenerator.java:119)
[01:32:25] [Worker-Main-5/WARN]: 	at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$7(ChunkStatus.java:77)
[01:32:25] [Worker-Main-5/WARN]: 	at net.minecraft.world.level.chunk.ChunkStatus$d.doWork(ChunkStatus.java:276)
[01:32:25] [Worker-Main-5/WARN]: 	at net.minecraft.world.level.chunk.ChunkStatus.a(ChunkStatus.java:212)
[01:32:25] [Worker-Main-5/WARN]: 	at net.minecraft.server.level.PlayerChunkMap.lambda$scheduleChunkGeneration$38(PlayerChunkMap.java:1365)
[01:32:25] [Worker-Main-5/WARN]: 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[01:32:25] [Worker-Main-5/WARN]: 	at net.minecraft.server.level.PlayerChunkMap.lambda$scheduleChunkGeneration$40(PlayerChunkMap.java:1363)
[01:32:25] [Worker-Main-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
[01:32:25] [Worker-Main-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[01:32:25] [Worker-Main-5/WARN]: 	at net.minecraft.server.level.ChunkTaskQueueSorter.lambda$message$1(ChunkTaskQueueSorter.java:58)
[01:32:25] [Worker-Main-5/WARN]: 	at net.minecraft.util.thread.ThreadedMailbox.g(ThreadedMailbox.java:87)
[01:32:25] [Worker-Main-5/WARN]: 	at net.minecraft.util.thread.ThreadedMailbox.a(ThreadedMailbox.java:141)
[01:32:25] [Worker-Main-5/WARN]: 	at net.minecraft.util.thread.ThreadedMailbox.run(ThreadedMailbox.java:96)
[01:32:25] [Worker-Main-5/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[01:32:25] [Worker-Main-5/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[01:32:25] [Worker-Main-5/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[01:32:25] [Worker-Main-5/INFO]: [Iris]: ======================================
[01:32:26] [Craft Scheduler Thread - 197 - Iris/WARN]: [Iris] Plugin Iris v1.8.10 generated an exception while executing task 26490
java.lang.NullPointerException: Cannot invoke "com.volmit.iris.engine.IrisComplex.getTrueBiomeStream()" because the return value of "com.volmit.iris.engine.framework.Engine.getComplex()" is null
	at com.volmit.iris.engine.framework.Engine.getSurfaceBiome(Engine.java:238) ~[?:?]
	at com.volmit.iris.engine.framework.Engine.getSurfaceBiome(Engine.java:539) ~[?:?]
	at com.volmit.iris.engine.IrisWorldManager.spawnIn(IrisWorldManager.java:279) ~[?:?]
	at com.volmit.iris.engine.IrisWorldManager.lambda$updateChunks$0(IrisWorldManager.java:190) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1299]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Purpur-1299]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Purpur-1299]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

### Minecraft Version

1.17.1

### Iris Version

1.8.10

### Log

.

**Comment by cyberpwnn** [comment]
It prefers this over freezing, a studio world is temporary, we dont want to waste time saving files if we're going to delete it in 5 seconds
