### ISSUE TITLE
Mythicmobs 5.0.x update their api

### ISSUE THREAD

**Issue by Fixed-cpu** [VolmitSoftware/Iris#772]
### Problem

When using newest version of mythicmobs, iris can't spawn it by old method because mythicmobs 5.0.x update their API.
Realbiome condition can't use either.

### Solution

[19:05:10 WARN]: java.lang.ClassNotFoundException: io.lumine.xikage.mythicmobs.MythicMobs
[19:05:10 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153)
[19:05:10 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105)
[19:05:10 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[19:05:10 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[19:05:10 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[19:05:10 WARN]:        at Iris-2.0.2-1.18.X.jar//com.volmit.iris.core.link.MythicMobsLink.spawnMob(MythicMobsLink.java:68)
[19:05:10 WARN]:        at Iris-2.0.2-1.18.X.jar//com.volmit.iris.engine.object.IrisEntity.doSpawn(IrisEntity.java:459)
[19:05:10 WARN]:        at Iris-2.0.2-1.18.X.jar//com.volmit.iris.engine.object.IrisEntity.lambda$doSpawn$6(IrisEntity.java:440)
[19:05:10 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[19:05:10 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[19:05:10 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1558)
[19:05:10 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:522)
[19:05:10 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1482)
[19:05:10 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1246)
[19:05:10 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320)
[19:05:10 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### Minecraft Version

1.18

### Iris Version

Iris-2.0.2

### Log

https://mclo.gs/jbP8XBg

**Comment by Keopsfenks** [comment]
The same is true in Realbiomecondition, please bring an update.

**Comment by NextdoorPsycho** [comment]
Fixing this on development Branch, DM me on Discord and ill reach out to anyone who can test it

**Comment by NextdoorPsycho** [comment]
I already sent the JAr to cyber so he should make spigot update an time now
