### ISSUE TITLE
Plugin Doesnt Generate

### ISSUE THREAD

**Issue by intisy** [VolmitSoftware/Iris#813]
### Problem

Every time ill generate an World the entire world is just flat "Red Glazed Terracotta" for some reason and gives me an error every time an chunk is generated

Error:
[21:11:32] [Worker-Main-14/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "com.volmit.iris.engine.data.cache.AtomicCache.aquire(java.util.function.Supplier)" is null
[21:11:32] [Worker-Main-14/WARN]:       at com.volmit.iris.engine.IrisEngineMantle.<init>(IrisEngineMantle.java:64)
[21:11:32] [Worker-Main-14/WARN]:       at com.volmit.iris.engine.IrisEngine.<init>(IrisEngine.java:127)
[21:11:32] [Worker-Main-14/WARN]:       at com.volmit.iris.engine.platform.BukkitChunkGenerator.setupEngine(BukkitChunkGenerator.java:126)
[21:11:32] [Worker-Main-14/WARN]:       at com.volmit.iris.engine.platform.BukkitChunkGenerator.getEngine(BukkitChunkGenerator.java:200)
[21:11:32] [Worker-Main-14/WARN]:       at com.volmit.iris.engine.platform.BukkitChunkGenerator.generateChunkData(BukkitChunkGenerator.java:272)
[21:11:32] [Worker-Main-14/WARN]:       at org.bukkit.craftbukkit.v1_18_R2.generator.CustomChunkGenerator.a(CustomChunkGenerator.java:166)
[21:11:32] [Worker-Main-14/WARN]:       at net.minecraft.world.level.chunk.ChunkStatus.lambda$8(ChunkStatus.java:125)
[21:11:32] [Worker-Main-14/WARN]:       at net.minecraft.world.level.chunk.ChunkStatus$d.doWork(ChunkStatus.java:331)
[21:11:32] [Worker-Main-14/WARN]:       at net.minecraft.world.level.chunk.ChunkStatus.a(ChunkStatus.java:273)
[21:11:32] [Worker-Main-14/WARN]:       at net.minecraft.server.level.PlayerChunkMap.lambda$28(PlayerChunkMap.java:667)
[21:11:32] [Worker-Main-14/WARN]:       at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[21:11:32] [Worker-Main-14/WARN]:       at net.minecraft.server.level.PlayerChunkMap.lambda$27(PlayerChunkMap.java:665)
[21:11:32] [Worker-Main-14/WARN]:       at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
[21:11:32] [Worker-Main-14/WARN]:       at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[21:11:32] [Worker-Main-14/WARN]:       at net.minecraft.server.level.ChunkTaskQueueSorter.b(SourceFile:62)
[21:11:32] [Worker-Main-14/WARN]:       at net.minecraft.util.thread.ThreadedMailbox.h(SourceFile:91)
[21:11:32] [Worker-Main-14/WARN]:       at net.minecraft.util.thread.ThreadedMailbox.a(SourceFile:146)
[21:11:32] [Worker-Main-14/WARN]:       at net.minecraft.util.thread.ThreadedMailbox.run(SourceFile:102)
[21:11:32] [Worker-Main-14/WARN]:       at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[21:11:32] [Worker-Main-14/WARN]:       at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[21:11:32] [Worker-Main-14/WARN]:       at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[21:11:32] [Worker-Main-14/WARN]:       at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[21:11:32] [Worker-Main-14/WARN]:       at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[21:11:32] [Worker-Main-14/WARN]:       at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[21:11:32] [Worker-Main-14/INFO]: [Iris]: ======================================

### Minecraft Version

1.18

### Iris Version

2.1.3 same with 2.2.0

### Log

https://mclo.gs/y3sQTbM

**Comment by svdgoor** [comment]
Atomic Cache Failure on the FAQ on the wiki.
Next time contact us through Discord for these issues, thank you.
