### ISSUE TITLE
Generating world via Toolbelt without sender generates exception

### ISSUE THREAD

**Issue by CDFN** [VolmitSoftware/Iris#824]
### Problem

1. Setup Iris 2.2.3 for Minecraft 1.19 on Purpur server
2. Use following code to create world:
```kt
                val world = IrisToolbelt.createWorld()
                    .name(data.id.toString())
                    .dimension("overworld")
                    .pregen(PregenTask.builder()
                        .center(Position2(0, 0))
                        .width(10)
                        .height(10)
                        .build()
                    )
                    .create()
```
3. We can observe exception is being thrown:
```
lobby       | java.lang.NullPointerException: Cannot invoke "com.volmit.iris.util.plugin.VolmitSender.sendMessage(String)" because "sender" is null
lobby       | 	at com.volmit.iris.core.service.StudioSVC.installIntoWorld(StudioSVC.java:86) ~[Iris-2.2.3-1.19.jar:?]
lobby       | 	at com.volmit.iris.core.tools.IrisCreator.create(IrisCreator.java:109) ~[Iris-2.2.3-1.19.jar:?]
lobby       | 	at dev.cdfn.screalms.bukkit.core.command.RealmCommandExecutor$onCommand$1.invokeSuspend(RealmCommandExecutor.kt:32) ~[bukkit-1.0.0-all.jar:?]
lobby       | 	at dev.cdfn.screalms.bukkit.core.command.RealmCommandExecutor$onCommand$1.invoke(RealmCommandExecutor.kt) ~[bukkit-1.0.0-all.jar:?]
lobby       | 	at dev.cdfn.screalms.bukkit.core.command.RealmCommandExecutor$onCommand$1.invoke(RealmCommandExecutor.kt) ~[bukkit-1.0.0-all.jar:?]
lobby       | 	at com.okkero.skedule.SchedulerCoroutineKt$schedule$block$1.invokeSuspend(SchedulerCoroutine.kt:31) ~[bukkit-1.0.0-all.jar:?]
lobby       | 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[bukkit-1.0.0-all.jar:?]
lobby       | 	at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:41) ~[bukkit-1.0.0-all.jar:?]
lobby       | 	at com.okkero.skedule.BukkitSchedulerController$start$2$1.invoke(SchedulerCoroutine.kt:64) ~[bukkit-1.0.0-all.jar:?]
lobby       | 	at com.okkero.skedule.BukkitSchedulerController$start$2$1.invoke(SchedulerCoroutine.kt:51) ~[bukkit-1.0.0-all.jar:?]
lobby       | 	at com.okkero.skedule.NonRepeatingTaskScheduler$doContextSwitch$1.invoke(SchedulerCoroutine.kt:222) ~[bukkit-1.0.0-all.jar:?]
lobby       | 	at com.okkero.skedule.NonRepeatingTaskScheduler$doContextSwitch$1.invoke(SchedulerCoroutine.kt:204) ~[bukkit-1.0.0-all.jar:?]
lobby       | 	at com.okkero.skedule.NonRepeatingTaskScheduler$forceNewContext$1.invoke(SchedulerCoroutine.kt:227) ~[bukkit-1.0.0-all.jar:?]
lobby       | 	at com.okkero.skedule.NonRepeatingTaskScheduler$forceNewContext$1.invoke(SchedulerCoroutine.kt:204) ~[bukkit-1.0.0-all.jar:?]
lobby       | 	at com.okkero.skedule.SchedulerCoroutineKt$sam$java_lang_Runnable$0.run(SchedulerCoroutine.kt) ~[bukkit-1.0.0-all.jar:?]
lobby       | 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.jar:git-Purpur-1713]
lobby       | 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.jar:git-Purpur-1713]
lobby       | 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.jar:?]
lobby       | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
lobby       | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
```

### Solution

In my opinion we should either handle `null` properly or allow creating and passing some kind of empty `VolmitSender` instance.

### Minecraft Version

1.19

### Iris Version

2.2.3

### Log

N/A

**Comment by Vatuu** [comment]
Fixed in 2.2.4

**Comment by CDFN** [comment]
To be honest, I'm not really satisfied with the fix that was implemented. IMO there should be choice if we want to even use a sender. I can propose PR i would be happy with if you want.

**Comment by NextdoorPsycho** [comment]
If you do I’ll merge it out here can look it over. We were talking when he
implemented this and we don’t Really know a more optimal way but we’d love
to see your spin
