### ISSUE TITLE
Jigsaw unable to set spawner block to a proper one

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#861]
### Problem

1. Let the jigsaw system spawn a dungeon
2. See that its still the pig spawner thats doing nothing
3. Cry

{
    "maxDepth": 1,
    "pieces": [
        "dungeon/dungeon_zombie"
    ],
    "lockY": 3,
    "feature": {"entitySpawners": ["silverfish"]}
}

### Solution

Fix it

### Minecraft Version

1.19

### Iris Version

LATEST

### Log

no log needed

**Comment by ghost** [comment]
This is the error message when you try to save a object with a set spawner. In this case a zombie spawner
```
[10:11:17 INFO]: ArMiN231 issued server command: /iris o save dimension=overworld name=jigsaw/dungeon/zombie overwrite=true
[10:11:17 WARN]: java.lang.IllegalStateException: Tile is null, asynchronous access? CraftBlock{pos=BlockPosition{x=269, y=-55, z=-354},type=SPAWNER,data=Block{minecraft:spawner},fluid=net.minecraft.world.level.material.FluidTypeEmpty@56cb479a}
[10:11:17 WARN]:        at com.google.common.base.Preconditions.checkState(Preconditions.java:590)
[10:11:17 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:92)
[10:11:17 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:78)
[10:11:17 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockStates.getBlockState(CraftBlockStates.java:278)
[10:11:17 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockStates.getBlockState(CraftBlockStates.java:236)
[10:11:17 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockStates.getBlockState(CraftBlockStates.java:221)
[10:11:17 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.block.CraftBlock.getState(CraftBlock.java:329)
[10:11:17 WARN]:        at Iris-2.2.12-1.19.2.jar//com.volmit.iris.engine.object.TileData.getTileState(TileData.java:73)
[10:11:17 WARN]:        at Iris-2.2.12-1.19.2.jar//com.volmit.iris.engine.object.IrisObject.setUnsigned(IrisObject.java:479)
[10:11:17 WARN]:        at Iris-2.2.12-1.19.2.jar//com.volmit.iris.core.service.WandSVC.createSchematic(WandSVC.java:88)
[10:11:17 WARN]:        at Iris-2.2.12-1.19.2.jar//com.volmit.iris.core.commands.CommandObject.save(CommandObject.java:362)
[10:11:17 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:11:17 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[10:11:17 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:11:17 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[10:11:17 WARN]:        at Iris-2.2.12-1.19.2.jar//com.volmit.iris.util.decree.virtual.VirtualDecreeCommand.lambda$invokeNode$7(VirtualDecreeCommand.java:484)
[10:11:17 WARN]:        at Iris-2.2.12-1.19.2.jar//com.volmit.iris.util.decree.virtual.VirtualDecreeCommand.invokeNode(VirtualDecreeCommand.java:494)
[10:11:17 WARN]:        at Iris-2.2.12-1.19.2.jar//com.volmit.iris.util.decree.virtual.VirtualDecreeCommand.invoke(VirtualDecreeCommand.java:389)
[10:11:17 WARN]:        at Iris-2.2.12-1.19.2.jar//com.volmit.iris.util.decree.virtual.VirtualDecreeCommand.invoke(VirtualDecreeCommand.java:415)
[10:11:17 WARN]:        at Iris-2.2.12-1.19.2.jar//com.volmit.iris.util.decree.virtual.VirtualDecreeCommand.invoke(VirtualDecreeCommand.java:415)
[10:11:17 WARN]:        at Iris-2.2.12-1.19.2.jar//com.volmit.iris.util.decree.virtual.VirtualDecreeCommand.invoke(VirtualDecreeCommand.java:377)
[10:11:17 WARN]:        at Iris-2.2.12-1.19.2.jar//com.volmit.iris.util.decree.DecreeSystem.call(DecreeSystem.java:137)
[10:11:17 WARN]:        at Iris-2.2.12-1.19.2.jar//com.volmit.iris.util.decree.DecreeSystem.lambda$onCommand$1(DecreeSystem.java:164)
[10:11:17 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[10:11:17 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[10:11:17 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:11:17 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[10:11:17 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[10:11:17 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by NextdoorPsycho** [comment]
you will need to do it in the find/replace when generating

**Comment by ghost** [comment]
> you will need to do it in the find/replace when generating

Can you test that and see if that fixed my issue?

**Comment by Vatuu** [comment]
Rarity works fine, it's a weight not a percentage chance. Maximum allowed is 512. Tested on 2.3.6.

**Comment by Vatuu** [comment]
Accidentally closed this.
