### ISSUE TITLE
REMOVE /iris studio clean 

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#871]
### Problem

The beautify command for the pack is broken somehow

### Solution

Fix it?

### Minecraft Version

1.19

### Iris Version

LATEST

### Log

no log needed

**Comment by Vatuu** [comment]
Can't replicate, please stop making this "No work pls fix" issues and actually describe the problem.

**Comment by ghost** [comment]
> Can't replicate, please stop making this "No work pls fix" issues and actually describe the problem.

```
[17:34:07 INFO]: ArMiN231 issued server command: /iris studio clean project=overworld
[17:34:13 INFO]: [Iris]: Failed to run async task
[17:34:13 WARN]: com.volmit.iris.util.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
[17:34:13 WARN]:        at Iris-2.2.12-1.19.2.jar//com.volmit.iris.util.json.JSONTokener.syntaxError(JSONTokener.java:435)
[17:34:13 WARN]:        at Iris-2.2.12-1.19.2.jar//com.volmit.iris.util.json.JSONObject.<init>(JSONObject.java:151)
[17:34:13 WARN]:        at Iris-2.2.12-1.19.2.jar//com.volmit.iris.util.json.JSONObject.<init>(JSONObject.java:278)
[17:34:13 WARN]:        at Iris-2.2.12-1.19.2.jar//com.volmit.iris.core.commands.CommandStudio$1.execute(CommandStudio.java:201)
[17:34:13 WARN]:        at Iris-2.2.12-1.19.2.jar//com.volmit.iris.core.commands.CommandStudio$1.execute(CommandStudio.java:197)
[17:34:13 WARN]:        at Iris-2.2.12-1.19.2.jar//com.volmit.iris.util.scheduling.jobs.QueueJob.execute(QueueJob.java:54)
[17:34:13 WARN]:        at Iris-2.2.12-1.19.2.jar//com.volmit.iris.util.scheduling.jobs.JobCollection.execute(JobCollection.java:47)
[17:34:13 WARN]:        at Iris-2.2.12-1.19.2.jar//com.volmit.iris.util.scheduling.J.lambda$afut$6(J.java:262)
[17:34:13 WARN]:        at Iris-2.2.12-1.19.2.jar//com.volmit.iris.util.scheduling.J.lambda$a$1(J.java:81)
[17:34:13 WARN]:        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[17:34:13 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[17:34:13 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[17:34:13 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[17:34:13 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[17:34:13 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```
>
![2022-08-26_17 35 23](https://user-images.githubusercontent.com/109753839/186941402-20e90bae-4269-4a50-817f-d62b9611e14a.png)

**Comment by NextdoorPsycho** [comment]
This command was not even supposed to be implemented. Im changing this to be remove

**Comment by Vatuu** [comment]
The deed is done.
