### ISSUE TITLE
Add support for --bukkit-settings

### ISSUE THREAD

**Issue by ThatOverPowered** [VolmitSoftware/Iris#877]
### Adding, Removing, or Changing

Adding

### Type of Modification

Adding this would prevent Iris buggin out and shouting a WARN on startup

### What are you trying to modify

There are some specific flags to relocate the server files: https://www.spigotmc.org/wiki/start-up-parameters/

When relocating the `bukkit.yml` a WARN is displayed and Iris bugs out.

`
[01:00:51 WARN]: java.io.FileNotFoundException: bukkit.yml (The system cannot find the specified file)
[01:00:51 WARN]:        at java.base/java.io.FileInputStream.open0(Native Method)
[01:00:51 WARN]:        at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
[01:00:51 WARN]:        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
[01:00:51 WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:126)
[01:00:51 WARN]:        at Iris-2.2.13-1.19.2.jar//com.volmit.iris.Iris.checkForBukkitWorlds(Iris.java:425)
[01:00:51 WARN]:        at Iris-2.2.13-1.19.2.jar//com.volmit.iris.Iris.lambda$enable$7(Iris.java:416)
[01:00:51 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[01:00:51 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[01:00:51 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1156)
[01:00:51 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310)
[01:00:51 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
`

### Alternatives

No alternatives.

**Comment by NextdoorPsycho** [comment]
Dont relocate the bukkit yml???
so many plugins require it to be in the static starting directory. moving it and having things break is like removing a CD from a tray and getting annoyed when the movie breaks
