### ISSUE TITLE
[Bug] overrideGlobalLoot

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#884]
### Problem

1. Use overrideGlobalLoot on region and biome
2. See the error
3. The region loot won't get popluated

Region loot
`"place": [
                "structures/swordnp2",
                "structures/swordnp1",
                "structures/swordnpstr2",
                "structures/swordnpstr1",
                "structures/giantportal1",
                "structures/giantportal2",
                "structures/giantportal3",
                "structures/megaportal1",
                "structures/megaportal2"
            ],
            "loot": ["structures/ruined-portal"],
            "overrideGlobalLoot": true,`

Biome loot
`            "place": [
                "structures/oruins1",
                "structures/oruins2",
                "structures/oruins3"
            ],
            "mode": "PAINT",
            "loot": [{"name": "structures/ocean-ruins"}],
            "overrideGlobalLoot": true`

Error
```
[12:49:04 INFO]: [Iris]: Atomic cache failure!
[12:49:04 WARN]: java.lang.NullPointerException: Cannot invoke "com.volmit.iris.engine.object.IrisObjectLoot.getName()" because "<local4>" is null
[12:49:04 WARN]:        at Iris-2.2.15-1.19.2.jar.jar//com.volmit.iris.engine.object.IrisObjectPlacement.lambda$getCache$1(IrisObjectPlacement.java:206)
[12:49:04 WARN]:        at Iris-2.2.15-1.19.2.jar.jar//com.volmit.iris.engine.data.cache.AtomicCache.aquire(AtomicCache.java:93)
[12:49:04 WARN]:        at Iris-2.2.15-1.19.2.jar.jar//com.volmit.iris.engine.object.IrisObjectPlacement.getCache(IrisObjectPlacement.java:202)
[12:49:04 WARN]:        at Iris-2.2.15-1.19.2.jar.jar//com.volmit.iris.engine.object.IrisObjectPlacement.getTable(IrisObjectPlacement.java:253)
[12:49:04 WARN]:        at Iris-2.2.15-1.19.2.jar.jar//com.volmit.iris.engine.framework.Engine.getLootTables(Engine.java:431)
[12:49:04 WARN]:        at Iris-2.2.15-1.19.2.jar.jar//com.volmit.iris.engine.framework.Engine.update(Engine.java:355)
[12:49:04 WARN]:        at Iris-2.2.15-1.19.2.jar.jar//com.volmit.iris.engine.framework.Engine.lambda$updateChunk$6(Engine.java:313)
[12:49:04 WARN]:        at Iris-2.2.15-1.19.2.jar.jar//com.volmit.iris.util.mantle.MantleChunk.lambda$iterate$0(MantleChunk.java:225)
[12:49:04 WARN]:        at Iris-2.2.15-1.19.2.jar.jar//com.volmit.iris.util.hunk.storage.PaletteHunk.iterateSync(PaletteHunk.java:61)
[12:49:04 WARN]:        at Iris-2.2.15-1.19.2.jar.jar//com.volmit.iris.util.hunk.storage.PaletteOrHunk.iterateSync(PaletteOrHunk.java:76)
[12:49:04 WARN]:        at Iris-2.2.15-1.19.2.jar.jar//com.volmit.iris.util.mantle.MantleChunk.iterate(MantleChunk.java:225)
[12:49:04 WARN]:        at Iris-2.2.15-1.19.2.jar.jar//com.volmit.iris.util.mantle.Mantle.iterateChunk(Mantle.java:256)
[12:49:04 WARN]:        at Iris-2.2.15-1.19.2.jar.jar//com.volmit.iris.engine.framework.Engine.lambda$updateChunk$7(Engine.java:308)
[12:49:04 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[12:49:04 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[12:49:04 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1519)
[12:49:04 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:485)
[12:49:04 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1443)
[12:49:04 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1213)
[12:49:04 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310)
[12:49:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[12:49:04 WARN]: [Iris] Task #45972 for Iris v2.2.15-1.19.2 generated an exception
java.lang.NullPointerException: Cannot read field "exact" because "<local3>" is null
        at com.volmit.iris.engine.object.IrisObjectPlacement.getTable(IrisObjectPlacement.java:257) ~[Iris-2.2.15-1.19.2.jar.jar:?]
        at com.volmit.iris.engine.framework.Engine.getLootTables(Engine.java:431) ~[Iris-2.2.15-1.19.2.jar.jar:?]
        at com.volmit.iris.engine.framework.Engine.update(Engine.java:355) ~[Iris-2.2.15-1.19.2.jar.jar:?]
        at com.volmit.iris.engine.framework.Engine.lambda$updateChunk$6(Engine.java:313) ~[Iris-2.2.15-1.19.2.jar.jar:?]        at com.volmit.iris.util.mantle.MantleChunk.lambda$iterate$0(MantleChunk.java:225) ~[Iris-2.2.15-1.19.2.jar.jar:?]
        at com.volmit.iris.util.hunk.storage.PaletteHunk.iterateSync(PaletteHunk.java:61) ~[Iris-2.2.15-1.19.2.jar.jar:?]
        at com.volmit.iris.util.hunk.storage.PaletteOrHunk.iterateSync(PaletteOrHunk.java:76) ~[Iris-2.2.15-1.19.2.jar.jar:?]
        at com.volmit.iris.util.mantle.MantleChunk.iterate(MantleChunk.java:225) ~[Iris-2.2.15-1.19.2.jar.jar:?]
        at com.volmit.iris.util.mantle.Mantle.iterateChunk(Mantle.java:256) ~[Iris-2.2.15-1.19.2.jar.jar:?]
        at com.volmit.iris.engine.framework.Engine.lambda$updateChunk$7(Engine.java:308) ~[Iris-2.2.15-1.19.2.jar.jar:?]        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1762]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1762]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1519) ~[purpur-1.19.2.jar:git-Purpur-1762]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.2.jar:git-Purpur-1762]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1443) ~[purpur-1.19.2.jar:git-Purpur-1762]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1213) ~[purpur-1.19.2.jar:git-Purpur-1762]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1762]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Solution

Fix it?

### Minecraft Version

1.19

### Iris Version

2.2.15

### Log

No log needed

**Comment by Vatuu** [comment]
Fixed in upcoming version.
