### ISSUE TITLE
FAWE updates don't show until the chunk is unloaded and reloaded

### ISSUE THREAD

**Issue by AmareseV1** [VolmitSoftware/Iris#914]
### Problem

1. Install Iris...
2. Install FAWE
3. Make edits using FAWE in a IRIS generated world
4. See the issue

(Error thrown in console)
[FastAsyncWorldEdit] Task #4479 for FastAsyncWorldEdit v2.4.5-SNAPSHOT-269;dc2db5f generated an exception
java.lang.UnsupportedOperationException: null
        at net.minecraft.server.level.ChunkHolder.getTickingChunkFuture(ChunkHolder.java:178) ~[?:?]
        at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R1.PaperweightPlatformAdapter.sendChunk(PaperweightPlatformAdapter.java:283) ~[FastAsyncWorldEdit-Bukkit-2.4.5-SNAPSHOT-269.jar:?]
        at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R1.PaperweightStarlightRelighter.postProcessChunks(PaperweightStarlightRelighter.java:193) ~[FastAsyncWorldEdit-Bukkit-2.4.5-SNAPSHOT-269.jar:?]
        at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R1.PaperweightStarlightRelighter.lambda$fixLighting$5(PaperweightStarlightRelighter.java:157) ~[FastAsyncWorldEdit-Bukkit-2.4.5-SNAPSHOT-269.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1794]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1794]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1794]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1794]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1794]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1794]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1794]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Solution

The problem comes from Iris, as FAWE works properly in all worlds not generated by Iris.

### Minecraft Version

1.19

### Iris Version

2.3.3-1.19.2

### Log

https://IdontHaveaLogBecausethelogsarenotrealletters.com

**Comment by TH3N3WN00B** [comment]
Have you tried using Iris 2.3.6 and Fawe snapshot version 296?

**Comment by NextdoorPsycho** [comment]
This is also Normal Vanilla / FAWE intended behavers in their code (you can ask, i did) they need to ensure the chunks are loaded first. not something we can fix
