### ISSUE TITLE
Placeholder %iris_biome_name% working only when player on some height? When the player is on the ground its showing: "A Biome".

### ISSUE THREAD

**Issue by Acrozi** [VolmitSoftware/Iris#929]
### Problem

Placeholder %iris_biome_name% working only when player on some height? When the player is on the ground its showing: "A Biome".

### Minecraft Version

1.18

### Iris Version

Iris 2.1.3

### Log

https://pastebin.com/NGGsVz5D

**Comment by Acrozi** [comment]
?

**Comment by RePixelatedMC** [comment]
Could you try this on the latest iris version so like 1.19.2. 

1.18 is discontinued iris only supports the latest versions

**Comment by Acrozi** [comment]
> Could you try this on the latest iris version so like 1.19.2.
> 
> 1.18 is discontinued iris only supports the latest versions

[08:44:22 ERROR]: Could not load 'plugins\Iris-2.3.8-1.19.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.19
        at org.bukkit.craftbukkit.v1_18_R2.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:375) ~[paper-1.18.2.jar:git-Paper-388]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:323) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

I get this error, is it working on 1.18.2?

**Comment by Acrozi** [comment]
Changed API version to 1.18 and it seems to be working!

**Comment by NextdoorPsycho** [comment]
https://gfycat.com/impossibleconcernedbrontosaurus
