### ISSUE TITLE
Crash when turning off server if player wasn't in the world

### ISSUE THREAD

**Issue by Acrozi** [VolmitSoftware/Iris#931]
### Problem

When i turning off my server so i get this fail if player wasn't in the world. Otherwise no fails. Any thought?

[17:01:39 INFO]: [Iris]: Mantle Size: 17 Chunks
[17:01:39 INFO]: [Iris]:   Object Mantle Size: 113 (8)
[17:01:39 INFO]: [Iris]:   Jigsaw Mantle Size: 156 (10)
[17:01:39 INFO]: [Iris]:   Carving Mantle Size: 265 (17)
[17:01:39 INFO]: [Iris]: Loaded Prefetch Cache to reduce generation disk use.
[17:01:39 INFO]: [Iris]: Initializing Engine: Lorwin/overworld (IrisRange(min=-64.0, max=448.0) height) Seed: -4456156505242590331
[17:01:39 INFO]: [Iris]: FAILED TO SETUP ENGINE!
[17:01:39 WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register IrisWorldManager(looper=null, id=0, updateQueue=null, cl=null, clw=null, ecl=null, cln=null, chunkUpdater=null, energy=0.0, entityCount=0, charge=0, actuallySpawned=0, cooldown=0, precount=null, injectBiomes=null) while not enabled
[17:01:39 WARN]:        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:699)
[17:01:39 WARN]:        at Iris-2.3.8-1.19.2.jar//com.volmit.iris.util.plugin.VolmitPlugin.registerListener(VolmitPlugin.java:454)
[17:01:39 WARN]:        at Iris-2.3.8-1.19.2.jar//com.volmit.iris.engine.framework.EngineAssignedWorldManager.<init>(EngineAssignedWorldManager.java:54)
[17:01:39 WARN]:        at Iris-2.3.8-1.19.2.jar//com.volmit.iris.engine.IrisWorldManager.<init>(IrisWorldManager.java:99)
[17:01:39 WARN]:        at Iris-2.3.8-1.19.2.jar//com.volmit.iris.engine.IrisEngine.setupEngine(IrisEngine.java:162)
[17:01:39 WARN]:        at Iris-2.3.8-1.19.2.jar//com.volmit.iris.engine.IrisEngine.<init>(IrisEngine.java:126)
[17:01:39 WARN]:        at Iris-2.3.8-1.19.2.jar//com.volmit.iris.engine.platform.BukkitChunkGenerator.setupEngine(BukkitChunkGenerator.java:178)
[17:01:39 WARN]:        at Iris-2.3.8-1.19.2.jar//com.volmit.iris.engine.platform.BukkitChunkGenerator.getEngine(BukkitChunkGenerator.java:259)
[17:01:39 WARN]:        at Iris-2.3.8-1.19.2.jar//com.volmit.iris.engine.platform.BukkitChunkGenerator.touch(BukkitChunkGenerator.java:324)
[17:01:39 WARN]:        at Iris-2.3.8-1.19.2.jar//com.volmit.iris.core.tools.IrisToolbelt.isIrisWorld(IrisToolbelt.java:95)
[17:01:39 WARN]:        at Iris-2.3.8-1.19.2.jar//com.volmit.iris.core.service.StudioSVC.onDisable(StudioSVC.java:76)
[17:01:39 WARN]:        at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780)
[17:01:39 WARN]:        at Iris-2.3.8-1.19.2.jar//com.volmit.iris.Iris.onDisable(Iris.java:539)
[17:01:39 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[17:01:39 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399)
[17:01:39 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:579)
[17:01:39 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:556)
[17:01:39 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.disablePlugins(CraftServer.java:499)
[17:01:39 WARN]:        at net.minecraft.server.MinecraftServer.s(MinecraftServer.java:943)
[17:01:39 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.s(DedicatedServer.java:808)
[17:01:39 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1212)
[17:01:39 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[17:01:39 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### Minecraft Version

1.19

### Iris Version

Iris-2.3.8-1.19.2

### Log

-

**Comment by NextdoorPsycho** [comment]
how were you able to cause this?

**Comment by ghost** [comment]
> how were you able to cause this?

I'm also experiencing the same problem, the issue occurs on a regular shutdown.

**Comment by ghost** [comment]
I'm also facing this same problem, if more information is needed please let me know.

**Comment by Acrozi** [comment]
> how were you able to cause this?

default shutdown. I use iris world like as second one.

**Comment by NextdoorPsycho** [comment]
I love how nobody read my request for "How were you able to cause this"
Because just "im having this problem too" is not helpful. 

What are the steps that you are doing to remake it.
1: start server
2: stop server 
etc...

**Comment by ghost** [comment]
> I love how nobody read my request for "How were you able to cause this" Because just "im having this problem too" is not helpful.
> 
> What are the steps that you are doing to remake it. 1: start server 2: stop server etc...

I've responded to your request, it occurs on a normal shutdown:
```
1.Start server
2.Stop server
3.See error
```

**Comment by NextdoorPsycho** [comment]
> > I love how nobody read my request for "How were you able to cause this" Because just "im having this problem too" is not helpful.
> > What are the steps that you are doing to remake it. 1: start server 2: stop server etc...
> 
> I've responded to your request, it occurs on a normal shutdown:
> 
> ```
> 1.Start server
> 2.Stop server
> 3.See error
> ```

Can't replicate it
https://gfycat.com/FixedDazzlingAmericanrobin The only error I get is because I forgot to update Rift

**Comment by NextdoorPsycho** [comment]
Feel Free to Make another COmment / Reopen this / Open a new one. I'm on latest everything and following your steps I cant reproduce it
