### ISSUE TITLE
Iris Console Error

### ISSUE THREAD

**Issue by evanonym0us** [VolmitSoftware/Iris#948]
### Problem

When joining the server, this appears in console. Is this to be expected?

[05:35:18 INFO]: [Iris]: Mantle Size: 15 Chunks
[05:35:18 INFO]: [Iris]:   Object Mantle Size: 113 (8)
[05:35:18 INFO]: [Iris]:   Jigsaw Mantle Size: 156 (10)
[05:35:18 INFO]: [Iris]:   Carving Mantle Size: 239 (15)
[05:35:18 INFO]: [Iris]: Loaded Prefetch Cache to reduce generation disk use.
[05:35:18 INFO]: [Iris]: Initializing Engine: world/overworld (IrisRange(min=-64.0, max=320.0) height) Seed: -2093692515
[05:35:18 INFO]: [Iris]: Failed to read Tectonic Plate /home/container/./world/mantle/p.0.ttp creating a new chunk instead.
[05:35:18 WARN]: java.io.UTFDataFormatException: malformed input around byte 1
[05:35:18 WARN]:        at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:661)
[05:35:18 WARN]:        at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:570)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.matter.MatterHeader.read(MatterHeader.java:41)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.matter.Matter.readDin(Matter.java:136)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.matter.Matter.readDin(Matter.java:111)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.MantleChunk.<init>(MantleChunk.java:83)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.TectonicPlate.<init>(TectonicPlate.java:74)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.TectonicPlate.read(TectonicPlate.java:84)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.Mantle.lambda$getSafe$4(Mantle.java:488)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.parallel.HyperLock.withResult(HyperLock.java:105)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.Mantle.lambda$getSafe$5(Mantle.java:475)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:436)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:979)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.Mantle.get(Mantle.java:444)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.Mantle.hasFlag(Mantle.java:242)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.Mantle.raiseFlag(Mantle.java:139)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.engine.IrisWorldManager.lambda$updateChunks$3(IrisWorldManager.java:194)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.scheduling.J.lambda$a$1(J.java:81)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[05:35:18 INFO]: [Iris]: Engine Panic reading.tectonic-plate: /home/container/./world/mantle/p.0.ttp
[05:35:18 INFO]: [Iris]: Engine Panic read-chunk: Chunk[0]
[05:35:18 INFO]: [Iris]: Engine Panic read.matter.size: 16x16x16777216
[05:35:18 INFO]: [Iris]: Engine Panic read.section: Section[2]
[05:35:18 INFO]: [Iris]: Engine Panic read.matter.slicecount: 0
[05:35:18 INFO]: [Iris]: Failed to read Tectonic Plate /home/container/./world/mantle/p.-4294967296.ttp creating a new chunk instead.
[05:35:18 WARN]: java.io.UTFDataFormatException: malformed input around byte 1
[05:35:18 WARN]:        at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:661)
[05:35:18 WARN]:        at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:570)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.matter.MatterHeader.read(MatterHeader.java:41)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.matter.Matter.readDin(Matter.java:136)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.matter.Matter.readDin(Matter.java:111)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.MantleChunk.<init>(MantleChunk.java:83)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.TectonicPlate.<init>(TectonicPlate.java:74)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.TectonicPlate.read(TectonicPlate.java:84)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.Mantle.lambda$getSafe$4(Mantle.java:488)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.parallel.HyperLock.withResult(HyperLock.java:105)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.Mantle.lambda$getSafe$5(Mantle.java:475)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:436)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:979)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.Mantle.get(Mantle.java:444)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.Mantle.hasFlag(Mantle.java:242)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.engine.mantle.EngineMantle.isCovered(EngineMantle.java:272)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.engine.mantle.EngineMantle.cleanupChunk(EngineMantle.java:282)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.engine.framework.Engine.lambda$cleanupMantleChunk$30(Engine.java:921)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.scheduling.J.lambda$a$1(J.java:81)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[05:35:18 INFO]: [Iris]: Engine Panic reading.tectonic-plate: /home/container/./world/mantle/p.-4294967296.ttp
[05:35:18 INFO]: [Iris]: Engine Panic read-chunk: Chunk[0]
[05:35:18 INFO]: [Iris]: Engine Panic read.matter.size: 16x16x16777216
[05:35:18 INFO]: [Iris]: Engine Panic read.section: Section[3]
[05:35:18 INFO]: [Iris]: Engine Panic read.matter.slicecount: 0
[05:35:18 INFO]: [Iris]: Failed to read Tectonic Plate /home/container/./world/mantle/p.-1.ttp creating a new chunk instead.
[05:35:18 WARN]: java.io.UTFDataFormatException: malformed input around byte 1
[05:35:18 WARN]:        at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:661)
[05:35:18 WARN]:        at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:570)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.matter.MatterHeader.read(MatterHeader.java:41)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.matter.Matter.readDin(Matter.java:136)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.matter.Matter.readDin(Matter.java:111)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.MantleChunk.<init>(MantleChunk.java:83)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.TectonicPlate.<init>(TectonicPlate.java:74)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.TectonicPlate.read(TectonicPlate.java:84)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.Mantle.lambda$getSafe$4(Mantle.java:488)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.parallel.HyperLock.withResult(HyperLock.java:105)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.Mantle.lambda$getSafe$5(Mantle.java:475)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:436)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:979)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.Mantle.get(Mantle.java:444)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.Mantle.hasFlag(Mantle.java:242)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.engine.mantle.EngineMantle.isCovered(EngineMantle.java:272)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.engine.mantle.EngineMantle.cleanupChunk(EngineMantle.java:282)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.engine.framework.Engine.lambda$cleanupMantleChunk$30(Engine.java:921)
[05:35:18 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.scheduling.J.lambda$a$1(J.java:81)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[05:35:18 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[05:35:18 INFO]: [Iris]: Engine Panic reading.tectonic-plate: /home/container/./world/mantle/p.-1.ttp
[05:35:18 INFO]: [Iris]: Engine Panic read-chunk: Chunk[0]
[05:35:18 INFO]: [Iris]: Engine Panic read.matter.size: 16x16x33554432
[05:35:18 INFO]: [Iris]: Engine Panic read.section: Section[2]
[05:35:18 INFO]: [Iris]: Engine Panic read.matter.slicecount: 0
[05:35:20 INFO]: [Iris]: Failed to read Tectonic Plate /home/container/./world/mantle/p.4294967295.ttp creating a new chunk instead.
[05:35:20 WARN]: java.io.UTFDataFormatException: malformed input around byte 1
[05:35:20 WARN]:        at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:661)
[05:35:20 WARN]:        at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:570)
[05:35:20 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.matter.MatterHeader.read(MatterHeader.java:41)
[05:35:20 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.matter.Matter.readDin(Matter.java:136)
[05:35:20 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.matter.Matter.readDin(Matter.java:111)
[05:35:20 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.MantleChunk.<init>(MantleChunk.java:83)
[05:35:20 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.TectonicPlate.<init>(TectonicPlate.java:74)
[05:35:20 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.TectonicPlate.read(TectonicPlate.java:84)
[05:35:20 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.Mantle.lambda$getSafe$4(Mantle.java:488)
[05:35:20 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.parallel.HyperLock.withResult(HyperLock.java:105)
[05:35:20 WARN]:        at Iris-2.3.13-1.19.3.jar//com.volmit.iris.util.mantle.Mantle.lambda$getSafe$5(Mantle.java:475)
[05:35:20 WARN]:        at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
[05:35:20 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[05:35:20 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[05:35:20 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[05:35:20 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[05:35:20 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[05:35:20 INFO]: [Iris]: Engine Panic reading.tectonic-plate: /home/container/./world/mantle/p.4294967295.ttp
[05:35:20 INFO]: [Iris]: Engine Panic read-chunk: Chunk[0]
[05:35:20 INFO]: [Iris]: Engine Panic read.matter.size: 16x16x50331648
[05:35:20 INFO]: [Iris]: Engine Panic read.section: Section[2]
[05:35:20 INFO]: [Iris]: Engine Panic read.matter.slicecount: 0

### Minecraft Version

1.19

### Iris Version

v2.3.13-1.19.3

### Log

https://paste.etechsystems.org/qodihozuni.yaml

**Comment by svdgoor** [comment]
The first 8 lines, yes. The rest definitely not.
I noticed you wrote down 1.19 for your MC version, but 1.19.3 for the Iris version.
Please remove the world (if that is still possible, i.e. there is no player buildings in that world you can't lose etc), update your server to 1.19.3 and then make the world again, with the 1.19.3 version of Iris you already have installed.
If this does not resolve your issue and the same errors appear, there is likely a mistake in the way the world is setup. In this event, please open this issue and we'll do our best to help out.

**Comment by svdgoor** [comment]
P.s. always send a full log, not just the part with the error. If the log is too long just send everything up to and including the error (so from the start).
