### ISSUE TITLE
 Downloaded file did not match expected hash

### ISSUE THREAD

**Issue by ilovend** [VolmitSoftware/Iris#984]
### Problem

When I tried to compile Iris using Gradle, I encountered an error. I tried to download the file, but found that its hash value did not match the required hash value for downloading (it's not the same file). I'm sorry, I don't know how to read code or solve this problem. I really need your help.

When attempting to download the Minecraft server file from the URL "https://piston-data.mojang.com/v1/objects/bc44f6dd84cd2f3ad8c0caad850eaca9e82067e3/server.txt", the downloaded file was saved as "work\minecraft_server.1.19.3.txt". However, the downloaded file's hash value "b995ab5a08b476645c83a84cbcefab7ad3948a3e" did not match the expected hash value "bc44f6dd84cd2f3ad8c0caad850eaca9e82067e3", resulting in the following error:

```
Exception in thread "main" java.lang.IllegalStateException: Downloaded file: work\minecraft_server.1.19.3.txt did not match expected hash: bc44f6dd84cd2f3ad8c0caad850eaca9e82067e3
	at org.spigotmc.builder.Builder.download(Builder.java:1172)
	at org.spigotmc.builder.Builder.download(Builder.java:1151)
	at org.spigotmc.builder.Builder.main(Builder.java:506)
	at org.spigotmc.builder.Bootstrap.main(Bootstrap.java:27)
```

![Snipaste_2023-04-03_12-14-57](https://user-images.githubusercontent.com/125713294/229417568-a835abd3-4961-4bd2-9bac-ab3ebe3a4728.png)

### Minecraft Version

1.14.X

### Iris Version

2.4.3

### Log

https://mclo.gs/ZsAo5uD

**Comment by ilovend** [comment]
Okay, I have pulled the latest update and tried version 2.5.0. I want to see if the issue still occurs.

**Comment by ilovend** [comment]
![Snipaste_2023-04-03_16-27-14](https://user-images.githubusercontent.com/125713294/229454322-9a5d40dc-b735-4afd-8548-729aab49b2ff.png)
It's strange that this error has reappeared in the 2.5.0 tag.

**Comment by ilovend** [comment]
![image](https://user-images.githubusercontent.com/125713294/229476809-95b83784-aab1-4f9d-bafd-2bd6a939bd70.png)
It's good now, but a new problem has arisen: 'getHandle(net.minecraft.world.level.chunk.ChunkStatus)' in 'org.bukkit.craftbukkit.v1_19_R3.CraftChunk' cannot be applied to '()'.
